http://dl.acm.org/citation.cfm?id=368387
http://penguin.ewu.edu/class/cscd300/Topic/AdvSorting/p30-shell.pdf
http://csg.sph.umich.edu/abecasis/class/2008/615.06.pdf
https://pt.wikipedia.org/wiki/Shell_sort
https://en.wikipedia.org/wiki/Shellsort
http://codisaster.com/pt/ordenacao-e-recuperacao/shell-sort/
http://www.cafw.ufsm.br/~bruno/disciplinas/estrutura_dados/slides/aula15_16_bubbleSort_shellSort.pdf
https://www.cs.cmu.edu/~adamchik/15-121/lectures/Algorithmic%20Complexity/complexity.html
https://www.youtube.com/watch?v=beYD4CW8giA
https://en.wikipedia.org/wiki/Sorting_algorithm
https://secweb.cs.odu.edu/~zeil/cs361/sum13/Public/shell/shell-printable.pdf
http://www.codingeek.com/algorithms/shell-sort-algorithm-explanation-implementation-and-complexity/